// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroHub.Data;

#nullable disable

namespace NeuroHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeuroHub.Models.AIPrompt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NeuralNetwork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AIPrompts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NeuralNetwork = "ChatGPT",
                            Price = 5m,
                            PromptText = "Напиши SEO-оптимізовану статтю на тему...",
                            Title = "Створити SEO статтю"
                        },
                        new
                        {
                            Id = 2,
                            NeuralNetwork = "Midjourney",
                            Price = 10m,
                            PromptText = "Створи логотип для IT компанії у стилі...",
                            Title = "Генерація логотипу"
                        },
                        new
                        {
                            Id = 3,
                            NeuralNetwork = "ChatGPT",
                            Price = 0m,
                            PromptText = "Проаналізуй і покращи цей код...",
                            Title = "Рефакторинг коду"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
